### ISSUE TITLE
wrong ip addr when there are 2 network

### ISSUE THREAD

**Issue by william-best** [wehotel/fizz-gateway-community#101]
when there are 2 or more networks, such as:
eth0: 1.1.1.1
docker0: 192.168.1.1

the manager use 192.168.1.1, but not eth0. I set gateway-urls: eth0:port in application-prod.yml

It is a bug, it will cause the gateway gropu cannot use. 

My suggestion:
1. show all gateway ips in  网关分组-defaule-网关实例IP,  why there is no value when fist use.
2. use Users config, no auto choose

**Comment by william-best** [comment]
your solution :serverIp = System.getenv(SERVER_IP) is not better,  my suggestion is : 
 In application.yml
server:
   net: ip/netmask <---- here
  port: 8600 

Why:
if you have 1  network:  net: 1.1.1.1
if you have N networks: net: 1.1.1.0/24  (find all nics, and choose one,. if you want better, load balance)
 Important:
show IPs in UI- manager

**Comment by dxfeng10** [comment]
A env variable is the fastest work around solution. Server ip is use as instance id,  you need to config it in each instance's config file if we do it in application.yml way, it is terrible when there are multiple instances, especially when using config center(apollo / nacos).  Manage the instance in UI-manager is the long-term solution, we will consider it in future, cuz it need more time to develop.
