### ISSUE TITLE
Add a token validation sample plugin base on fizz-spring-boot-starter

### ISSUE THREAD

**Issue by dxfeng10** [wehotel/fizz-gateway-community#209]
Add a token validation sample plugin base on fizz-spring-boot-starter:  

1. validate token by Redis
2. validate token by calling API

**Comment by hongqiaowei** [comment]
see https://github.com/wehotel/fizz-examples/commit/7435dfc0ca4bf96ee4fdf528ce2fd61b29c3dbdb
