### ISSUE TITLE
文档描述生成不对

### ISSUE THREAD

**Issue by lyx2014** [wehotel/fizz-gateway-community#403]
![image](https://user-images.githubusercontent.com/8734297/155040294-645bc80a-9aaf-44d4-b964-f64563c54c17.png)
但是 我文档描述不是这个！
![image](https://user-images.githubusercontent.com/8734297/155040349-98335ba1-b77f-47d7-88be-53cdb8f80e2d.png)

**Comment by simply4784** [comment]
第一张截图是接口文档的描述，而第二种截图是文档集的描述。他们指的不是同一个描述。
