### ISSUE TITLE
文档集接口生成错误

### ISSUE THREAD

**Issue by lyx2014** [wehotel/fizz-gateway-community#404]
我接口文档如下
 
![_QME9%@39`I L6U)JZJ% 1Q](https://user-images.githubusercontent.com/8734297/155040464-330ea530-20ab-4967-a4ea-c4daddb94766.png)
而文档集显示就只有patch接口 其他 都变成了patch
![OP`$IWL}QJKEJS V 0O_NKW](https://user-images.githubusercontent.com/8734297/155040526-2d710e9e-6247-440a-b496-441c118f7560.png)

**Comment by lyx2014** [comment]
这样无法支持一个接口2种以上的方法调用！

**Comment by simply4784** [comment]
切换到 “调试” 面板，“请求方法”是下拉选择框，支持切换选择。如果想使用get或post方法来调用，切换下请求方法就可以了。
