### ISSUE TITLE
文档调试问题

### ISSUE THREAD

**Issue by lyx2014** [wehotel/fizz-gateway-community#405]
文档集调试调用的 v2/api-docs地址 也就是 接口读取地址 ，无法使用像SWAGGER那样直接使用API 地址，比如 读取接口地址：
 http://172.0.0.1:6666/fizz-manager/v2/api-docs?group
里面 登录接口 使用 是 http://172.0.0.1:6666/fizz-manager/login,  可是 文档调试地址是http://172.0.0.1:6666/fizz-manager/v2/api-docs/login  ！

**Comment by zhong-jie** [comment]
调试页面发起的请求地址是从环境信息中获取的（后台 文档管理 > 环境信息），自查下环境信息请求地址是不是多配置了/v2/api-docs这样的后缀。
