### ISSUE TITLE
容器日志不能正常打印，打印的内容如下，如果想看日志还需要进终端通过命令查看

### ISSUE THREAD

**Issue by superbing** [wehotel/fizz-gateway-community#406]
cat: /opt/fizz-gateway-community/logs/tpid: No such file or directory

 Usage: grep [OPTION]... PATTERN [FILE]...

 Try 'grep --help' for more information.

 Usage: grep [OPTION]... PATTERN [FILE]...

 Try 'grep --help' for more information.

 starting fizz-gateway-community.jar ...

 tail: unrecognized file system type 0x794c7630 for ‘dummy.log’. please report this to bug-coreutils@gnu.org. reverting to polling

**Comment by dxfeng10** [comment]
released in v2.6.0
