### ISSUE TITLE
特殊情况下会产生NullPointException

### ISSUE THREAD

**Issue by linzhiqiang0514** [wehotel/fizz-gateway-community#409]
# 异常内容
```
Caused by: java.lang.NullPointerException
	... 1 more
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoReduceSeed] :
	reactor.core.publisher.Flux.reduce(Flux.java:6992)
```

# 产生原因
step.java
Line 135
当 component判断，可以执行，但是needRun判断为false时。
返回 Mono.just(new HashMap())

会导致在
Pipeline.java
Line 219 220.
处理结果对齐时，获取到空白map，导致无法获取input，继而产生空指针异常。

# 处理方式
第一步：
在
Pipeline.java
Line 219 220.
判断 map为空时，或者map.size=0时，不做处理。
建议增加一个warn输出。

第二步：
step.java
Line 135
修改返回，不返回Mono.jush(new HashMap())，而是与下面的ComponentResult一样，返回一个data为new Hashmap的新Map对象。

**Comment by dxfeng10** [comment]
fixed in v2.6.0
