### ISSUE TITLE
表达式解析有bug

### ISSUE THREAD

**Issue by gxproject** [wehotel/fizz-gateway-community#419]
FuncExecutor类
hasCloseParenthesis方法,应修改如下，否则第一个不是）就直接返回false了
for (int i = fromIndex; i < strLen; i++) {
            if (!Character.isWhitespace(argsStr.charAt(i))) {
                if (")".equals(String.valueOf(argsStr.charAt(i)))) {
                    return true;
                }
            }
        }

**Comment by dxfeng10** [comment]
@gxproject 这个方法是用于判断函数的结束标记符), 在右括号前可以有空格，但不可以是非空格外的字符。请提供有问题的表达式用于测试。

**Comment by gxproject** [comment]
> hasCloseParenthesis

"fn.string.toUpperCase(fn.codec.sha256(fn.string.concat(\"a\",\"b\",fn.date.timestamp())))"

**Comment by gxproject** [comment]
> @gxproject 这个方法是用于判断函数的结束标记符), 在右括号前可以有空格，但不可以是非空格外的字符。请提供有问题的表达式用于测试。
表达式如下：
"fn.string.toUpperCase(fn.codec.sha256(fn.string.concat(\"a\",\"b\",fn.date.timestamp())))"

**Comment by dxfeng10** [comment]
@gxproject 不是hasCloseParenthesis方法的问题，是因为无参函数或可变参数函数引起的，已修复。

**Comment by gxproject** [comment]
验证通过，可以了
