### ISSUE TITLE
打开调试模式后，日志在哪里看？

### ISSUE THREAD

**Issue by czcz1024** [wehotel/fizz-gateway-community#453]
文档中说，打开调试模式后，请求响应的详细信息可以在日志中看到。
日志在哪里查看？是有界面菜单进入，还是需要到docker linux的什么地方查看？

我在 网关日志 页面，进入后提示“未启用网关日志功能，如需使用请在设置管理里开启。”
但是我到 设置管理 页面，发现 接口统计 推送日志 都是enable的。其他没有什么额外的设置了，这个是什么问题？

**Comment by dxfeng10** [comment]
1、推送日志的开关的默认值没生效，设置管理页面点编辑重新保存一下
2、或到宿主机的日志映射目录./docker_volumes/fizz-gateway-community/logs下查看本地日志
