### ISSUE TITLE
Support sidecar traffic limit and ACL  服务治理需求应用场景（ACL、流控、RT/QPS统计等）

### ISSUE THREAD

**Issue by yyt701** [wehotel/fizz-gateway-community#56]
1. 我们目前有这样普遍紧急一个场景，需要 acl与流控，  项目A-client  注册到nacos    调用 项目B-server 注册到nacos， A与B都是内部业务系统服务，可以理解 两个微服务；

2. 有一大部分业务场景（如金融业务场景） api 很敏感，需要权限控制只允许指定的业务客户端可以访问；

最后希望 ：服务网关在服务治理方面也有它的发挥作用的地方

**Comment by linwaiwai** [comment]
Istio supports this function for it use sidecar as  a proxy to monitor all the traffics and can easily set a traffic limit into the service. Fizz can implement this function in another way for it is not sidecar proxy but a global entrance proxy. I am thinking adding fizz client sdk to help developer add the service traffic limit function without much effects. The client sdk will set and update the traffic limit according the config from the fizz backend. Meanwhile, it will report the traffic data to Fizz .But this method will invade the business code.

**Comment by linwaiwai** [comment]
fizz has implemented the traffic limit，but it is not slide car mode which I think now it is not ready to mass use in production env. ACL 、RT/QPS are not in the road map of fizz.
