### ISSUE TITLE
Compotent upgrade 

### ISSUE THREAD

**Issue by jayluns** [wehotel/fizz-gateway-community#6]
May be Apollo and euraka can be upgraded to nacos  be better, euraka's open source code gradually abandoned maintenance

**Comment by dxfeng10** [comment]
will support Nacos later

**Comment by qiangjinjiu** [comment]
It's maybe feature of  service discovery, it should be compatiable with K8S or docker?

**Comment by dxfeng10** [comment]
@jayluns supported Nacos from v1.2.0

**Comment by jayluns** [comment]
Wonderful.
product iteration is so&nbsp; fast...



Changelog:

support Nacos service discovery and config center
support running without service register center and set eureka as optional
support API statistic
support redirect in aggregation
support running fizz manager in Windows OS
return exception information while failed to execute script
add embedded default common.js in classpath
Fixed fizz manager startup error due to database case sensitivity
Fixed the duplicated records Bug in route management module






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wehotel/fizz-gateway-community"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月30日(星期一) 上午10:25
收件人:&nbsp;"wehotel/fizz-gateway-community"<fizz-gateway-community@noreply.github.com&gt;;
抄送:&nbsp;"蒋勇。"<perl_luck@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [wehotel/fizz-gateway-community] Compotent upgrade  (#6)





 
@jayluns supported Nacos from v1.2.0
