### ISSUE TITLE
Support custom the "proxy" field of the access url for gateway

### ISSUE THREAD

**Issue by xxd763795151** [wehotel/fizz-gateway-community#67]
> 网关访问地址格式为: http://{fizz网关ip:port}/proxy/{前端服务名}/{前端API路径}

I`m looking for a new gateway to replace our old gateway. 
The new gateway should be compitable with the route rule of old  gateway, but the format of the access url for fizz that is too fixed. It have to use "proxy" field in the url, and do not support config or do not use the field.

**Comment by dxfeng10** [comment]
Released in v1.5.0
