### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by xiaochi-xiaochi** [wehotel/fizz-gateway-community#7]
按照部署教程部署之后, 访问 http://ip:8000/fizz-manager/ (我的ip, 我部署在阿里云主机上, 使用的公网ip)
会出现以下错误, 咨询一下如何解决

code | 404
-- | --
success | false
data | {}
msg | "No handler found for GET /fizz-manager/"

**Comment by xiaochi-xiaochi** [comment]
服务已经正常启动, 8000端口也在监听
netstat -nltp|grep 8000
tcp6       0      0 :::8000                 :::*                    LISTEN      3458/java

**Comment by zhong-jie** [comment]
你好，fizz-manager是管理后台的后端服务，需要按步骤再安装管理后台的前端fizz-admin-professional服务，通过前端fizz-admin-professional服务入口访问管理后台，这边稍后更新安装文档。

**Comment by xiaochi-xiaochi** [comment]
我是安装部署教程将管理后台的前端放在了/home/data/fizzAdmin/下,如图
![1](https://user-images.githubusercontent.com/73106584/96534691-d1ef2c00-12c2-11eb-9586-6291d45b7fdf.jpg)

然后将后端服务放在了如图
![2](https://user-images.githubusercontent.com/73106584/96534759-f6e39f00-12c2-11eb-8a52-ab0b763d8870.jpg)

**Comment by xiaochi-xiaochi** [comment]
另外 冒昧问一下, 是否有交流群或者什么的, 方便咨询问题

**Comment by crazycarry** [comment]
这没有啥东西界面直接就只提供下载，你至少先捆绑点用户

**Comment by linwaiwai** [comment]
> 另外 冒昧问一下, 是否有交流群或者什么的, 方便咨询问题

交流群已经创建。512164278

**Comment by xiaochi-xiaochi** [comment]
> > 另外 冒昧问一下, 是否有交流群或者什么的, 方便咨询问题
> 
> 交流群已经创建。512164278

好的, 申请了, 通过一下
