### ISSUE TITLE
Could support docker in v1.5.x

### ISSUE THREAD

**Issue by william-best** [wehotel/fizz-gateway-community#71]
Our team want use fizz with docker, but it will support in v1.6.x, could you move it to 1.5.x?

**Comment by william-best** [comment]
we use python and go , none know java, so it is difficult to setup env.

**Comment by linwaiwai** [comment]
1.5.1 will be release recently. And the 1.6.1  will come soon. And now we have the binary package . You don't need compile it .All you need is to put the two packages in your machine, then start it .

**Comment by william-best** [comment]
Thanks for your reply.  I have download these 2 zips.  Could you give the users  a standard guide On ReadMe.md or Doc. For example:
1. manager and gateway not on  localhost 
2. one manger is  in a host-1,  2 gateway in 2 hosts(host-2/host-3).
3. mysql is Ali Cloud
4.  redis is Ali Cloud
5.  Apollo enable
6. Eureka enable

And when give docker guide, it should be the same as above, because we try to use it in production env, not only test.

**Comment by linwaiwai** [comment]
2.0.0 has supported docker.
