### ISSUE TITLE
Need backend service group

### ISSUE THREAD

**Issue by william-best** [wehotel/fizz-gateway-community#82]
when using service orchestration, users should input http://ip:port/xxxxx (backend service), such as
1. default env
2. test env
3. production env 

what we want to input :
1. default group
2. test group
3. ....

group means several backend ip:port with rotation and health check

**Comment by dxfeng10** [comment]
You could replace ip:port with service name if you are using service discovery,  such as:  http://order-service/order/getOrderList .  It will support to input multiple instance URLs for non service discovery case in later version
